### ISSUE TITLE
Add entire contents of playlist to room

### ISSUE THREAD

**Issue by macrivello** [pdaddyo/soundbounce-v2#66] opened 2017-12-05 07:30 UTC
First of all, great work, this is awesome. I was looking into building something like this and eventually found this project. It's sure a heck of a lot better than what I could make! 

I'm thinking it would be nice to add a playlist to a room. Perhaps playlists are searched in the main search component with the results displayed alongside, although logically separate from, the track results. Selecting a playlist will add all of the tracks contained in the playlist. 

The Spotify API looks like it should make this pretty straightforward. https://developer.spotify.com/web-api/playlist-endpoints/

I apologize if this feature is already implemented somewhere. I looked but didn't find it.

**Comment by pdaddyo** [comment] 2017-12-05 08:18
This is not yet implemented, but it is on the list under Room Config, where you'll be able to set a playlist to feed a room.  V1 of SB did this, I just haven't got round to it on v2 just yet!  Thanks for your support :)

**Comment by pdaddyo** [comment] 2017-12-05 08:18
Dupe of #9

**Closed by pdaddyo** 2017-12-05 08:18 UTC
Labels: duplicate
